name: testpkg
description: A package used for testing, and not much else.
version: 2.0.0
repository: https://github.com/miksen/testpkg

environment:
  sdk: '>=3.0.0-348 <4.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0

funding:
  - https://www.buymeacoffee.com/tactili
 
