name: Dart

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
  - cron: "0 0 * * 0" # Run every Sunday at 00:00.

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        # Test latest stable, beta, dev channels + last stable release
        # prior to the introduction of the unified `dart` developer tool.
        sdk: [stable, beta]
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          sdk: ${{ matrix.sdk }}

      - name: Analyze
        run: dart analyze
